### ISSUE TITLE
AttributeError under Python 3.9

### ISSUE THREAD

**Issue by freakboy3742** [beeware/gbulb#56]
**Describe the bug**

Via @leggewie:

Running the BeeWare tutorial 7 yields the following error:
```
Exception in callback ReadTransport._loop_reading(<Future pendi...op_reading()]>)
handle: <GLibHandle ReadTransport._loop_reading(<Future pendi...op_reading()]>)>
Traceback (most recent call last):
  File "/home/leggewie/.local/lib/python3.9/site-packages/gbulb/transports.py", line 146, in _loop_reading
    data = fut.result()  # Deliver data later in "finally" clause
asyncio.exceptions.InvalidStateError: Result is not set.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/leggewie/.local/lib/python3.9/site-packages/gbulb/transports.py", line 170, in _loop_reading
    except futures.InvalidStateError:
AttributeError: module 'asyncio.futures' has no attribute 'InvalidStateError'
Exception in callback ReadTransport._loop_reading(<Future finis...xe3\xc8j\xd0'>)
handle: <GLibHandle ReadTransport._loop_reading(<Future finis...xe3\xc8j\xd0'>)>
Traceback (most recent call last):
  File "/home/leggewie/.local/lib/python3.9/site-packages/gbulb/transports.py", line 140, in _loop_reading
    assert self._read_fut is fut or (
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/leggewie/.local/lib/python3.9/site-packages/gbulb/transports.py", line 170, in _loop_reading
    except futures.InvalidStateError:
AttributeError: module 'asyncio.futures' has no attribute 'InvalidStateError'
```

**To Reproduce**

Run BeeWare Tutorial 7

**Expected behavior**

No error; async HTTP requests complete.

**Environment:**
 - Operating System: Ubuntu 22.4?
 - Python version: 3.9
 - Software versions:
   - gbulb: 0.6.2

**Comment by freakboy3742** [comment]
Investigating further; `asyncio.futures.InvalidStateError` exists in Python 3.7, but not 3.8. However, `asyncio.InvalidStateError` exists on 3.6.

**Comment by leggewie** [comment]
Thank you very much.  I can confirm that #57 fixes this issue.
